# Generated by Django 5.2.17 on 2026-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato')], max_length=10)),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10)),
                ('idade', models.CharField(choices=[('filhote', 'Filhote'), ('adulto', 'Adulto')], max_length=10)),
                ('distancia', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('vacinado', models.BooleanField(default=False)),
                ('castrado', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True)),
                ('temperamento', models.CharField(blank=True, max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
