# Generated by Django 5.2.17 on 2026-09-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adotante', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('ja_teve_animais', models.BooleanField(default=False)),
                ('local_moradia', models.CharField(max_length=200)),
                ('possui_espaco', models.BooleanField(default=False)),
                ('todos_concordam', models.BooleanField(default=False)),
                ('consegue_cuidar', models.BooleanField(default=False)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='app.pet')),
            ],
        ),
    ]
