# Generated by Django 5.2.17 on 2026-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pet_latitude_pet_longitude_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='zona_rural',
            field=models.BooleanField(default=False),
        ),
    ]
