# Generated by Django 5.2.17 on 2026-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_perfilusuario_zona_rural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='distancia',
        ),
        migrations.AddField(
            model_name='pet',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='pet',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='rua',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pet',
            name='zona_rural',
            field=models.BooleanField(default=False),
        ),
    ]
